prgrms-web-devcourse-final-project/WEB4_5_GPT_BE

backend/src/main/resources/application.yml

개발서버 swagger 문서 확인용 cors 추가

---

backend/src/main/java/com/WEB4_5_GPT_BE/unihub/domain/member/controller/MemberController.java

로그아웃
마이페이지 기능
@SecurityRequirement(name = "accessToken을 사용한 bearerAuth 로그인 인증")
추가

 토큰 인증 swagger

---

backend/src/main/resources/application.yml

feat: cors 허용 도메인추가

---

.github/workflows/deploy-stg.yml
backend/src/main/java/com/WEB4_5_GPT_BE/unihub/global/config/springDoc/ForwardedHeaderConfig.java
infra/prod/main.tf
infra/stg/main.tf

Swagger ui 에서 CORS 문제로 테스트가 불가하던 문제 해결

---

backend/src/main/java/com/WEB4_5_GPT_BE/unihub/global/config/springDoc/ForwardedHeaderConfig.java
infra/prod/main.tf
infra/stg/main.tf

* fix : ForwardedHeaderConfig를 추가하고 서버 ha-proxy 설정에 X-Forwarded-Proto를 https로 설정
- http에 대한 요청이 들어오면 https로 변경해주도록 구현
* docs : stg 서버에 테스트 해보기 위해 옥정현/fix-70 브랜치를 deploy-stg에 추가
* docs : stg 서버에 테스트 완료 후 옥정현/fix-70 브랜치 제거

Swagger ui 에서 CORS 문제로 테스트가 불가하던 문제 해결 (#76)

---

backend/src/main/java/com/WEB4_5_GPT_BE/unihub/domain/member/dto/response/AdminLoginResponse.java
backend/src/main/java/com/WEB4_5_GPT_BE/unihub/domain/member/dto/response/MemberLoginResponse.java
backend/src/main/java/com/WEB4_5_GPT_BE/unihub/domain/member/service/AuthServiceImpl.java
backend/src/main/resources/application.yml
backend/src/test/java/com/WEB4_5_GPT_BE/unihub/domain/member/service/AuthTokenServiceTest.java

로그인, 관리자 로그인시 id, email, role을 response하도록 추가

로그인, 관리자 로그인시 id, email, role을 response하도록 추가

---

backend/src/main/java/com/WEB4_5_GPT_BE/unihub/domain/member/dto/response/AdminLoginResponse.java
backend/src/main/java/com/WEB4_5_GPT_BE/unihub/domain/member/dto/response/MemberLoginResponse.java
backend/src/main/java/com/WEB4_5_GPT_BE/unihub/domain/member/service/AuthServiceImpl.java
backend/src/main/java/com/WEB4_5_GPT_BE/unihub/global/config/springDoc/ForwardedHeaderConfig.java
backend/src/test/java/com/WEB4_5_GPT_BE/unihub/domain/member/service/AuthTokenServiceTest.java
infra/prod/main.tf
infra/stg/main.tf

Cors관련 오류 수정
로그인시 id, title, email에 대한 내용을 main으로 push

로그인시 id, title, email에 대한 내용 및 Cors관련 오류 수정 한 내용을 main으로 push

---

backend/src/main/java/com/WEB4_5_GPT_BE/unihub/global/init/InitDevData.java
backend/src/main/java/com/WEB4_5_GPT_BE/unihub/global/init/InitProdOrStgData.java

https://www.notion.so/1ec3550b7b55808b855ed808a9e42cb5?pvs=4
초기데이터 추가한 뒤
팀 노션 페이지에 테스트 데이터 정보 페이지를 만들어두었습니다.
운영서버에 대한 init 데이터가 변경되면 최신화 해주고
프론트 개발자님께 공유하면 좋을 것 같습니다.

feat: 개발, 테스트 및 운영서버에 초기 데이터 추가

---

backend/src/main/java/com/WEB4_5_GPT_BE/unihub/global/security/SecurityConstants.java

전공 및 대학 조회시 로그인이 필요없도록 수정

---

backend/src/main/java/com/WEB4_5_GPT_BE/unihub/domain/course/entity/Course.java
backend/src/main/java/com/WEB4_5_GPT_BE/unihub/domain/enrollment/controller/EnrollmentController.java
backend/src/main/java/com/WEB4_5_GPT_BE/unihub/domain/enrollment/service/EnrollmentService.java
backend/src/main/java/com/WEB4_5_GPT_BE/unihub/global/init/InitDataHelper.java
backend/src/main/java/com/WEB4_5_GPT_BE/unihub/global/security/SecurityConstants.java
backend/src/test/java/com/WEB4_5_GPT_BE/unihub/domain/enrollment/controller/EnrollmentControllerTest.java
backend/src/test/java/com/WEB4_5_GPT_BE/unihub/domain/enrollment/service/EnrollmentServiceTest.java

수강 신청, 취소하는 경우에
해당 강의에 현재 수강 인원(enrolled)가 변동되는 로직이 빠져있어
추가로 구현하고 테스트 케이스 추가하였습니다.

수강신청, 취소 시 누락된 강의 수강 인원 증감 로직 추가함

---

backend/src/main/java/com/WEB4_5_GPT_BE/unihub/domain/course/entity/Course.java
backend/src/main/java/com/WEB4_5_GPT_BE/unihub/domain/course/entity/EnrollmentPeriod.java
backend/src/main/java/com/WEB4_5_GPT_BE/unihub/domain/enrollment/controller/EnrollmentController.java
backend/src/main/java/com/WEB4_5_GPT_BE/unihub/domain/enrollment/service/EnrollmentService.java
backend/src/main/java/com/WEB4_5_GPT_BE/unihub/domain/member/dto/response/AdminLoginResponse.java
backend/src/main/java/com/WEB4_5_GPT_BE/unihub/domain/member/dto/response/MemberLoginResponse.java
backend/src/main/java/com/WEB4_5_GPT_BE/unihub/domain/member/dto/response/mypage/CourseScheduleResponse.java
backend/src/main/java/com/WEB4_5_GPT_BE/unihub/domain/member/service/AuthServiceImpl.java
backend/src/main/java/com/WEB4_5_GPT_BE/unihub/domain/university/controller/MajorController.java
backend/src/main/java/com/WEB4_5_GPT_BE/unihub/domain/university/controller/UniversityController.java
backend/src/main/java/com/WEB4_5_GPT_BE/unihub/global/config/springDoc/ForwardedHeaderConfig.java
backend/src/main/java/com/WEB4_5_GPT_BE/unihub/global/init/InitDataHelper.java
backend/src/main/java/com/WEB4_5_GPT_BE/unihub/global/init/InitDevData.java
backend/src/main/java/com/WEB4_5_GPT_BE/unihub/global/init/InitProdOrStgData.java
backend/src/main/java/com/WEB4_5_GPT_BE/unihub/global/security/SecurityConstants.java
backend/src/test/java/com/WEB4_5_GPT_BE/unihub/domain/enrollment/controller/EnrollmentControllerTest.java
backend/src/test/java/com/WEB4_5_GPT_BE/unihub/domain/enrollment/service/EnrollmentServiceTest.java
backend/src/test/java/com/WEB4_5_GPT_BE/unihub/domain/member/service/AuthTokenServiceTest.java
infra/prod/main.tf
infra/stg/main.tf

develop main 브랜치 동기화

---

backend/src/main/java/com/WEB4_5_GPT_BE/unihub/domain/admin/controller/AdminController.java
backend/src/main/java/com/WEB4_5_GPT_BE/unihub/domain/enrollment/controller/EnrollmentEventController.java
backend/src/test/java/com/WEB4_5_GPT_BE/unihub/domain/enrollment/controller/EnrollmentEventControllerTest.java

강을찬/fix 버그와 api명세서와 다른것 수정

---

backend/src/main/java/com/WEB4_5_GPT_BE/unihub/domain/admin/controller/AdminController.java
backend/src/main/java/com/WEB4_5_GPT_BE/unihub/global/security/SecurityConfig.java

관리자 api PreAuthorize 추가해 관리자만 접근 가능하도록 수정

[feat] 관리자 api PreAuthorize 추가해 관리자만 접근 가능하도록 수정

---

backend/src/main/java/com/WEB4_5_GPT_BE/unihub/domain/member/dto/response/mypage/ProfessorProfileResponse.java
backend/src/main/java/com/WEB4_5_GPT_BE/unihub/domain/member/dto/response/mypage/StudentProfileResponse.java

studentprofilereponse,professorprofilereponse에 university_id 추가

---

backend/src/main/java/com/WEB4_5_GPT_BE/unihub/domain/admin/controller/AdminController.java
backend/src/main/java/com/WEB4_5_GPT_BE/unihub/domain/enrollment/controller/EnrollmentEventController.java
backend/src/main/java/com/WEB4_5_GPT_BE/unihub/domain/member/dto/response/mypage/ProfessorProfileResponse.java
backend/src/main/java/com/WEB4_5_GPT_BE/unihub/domain/member/dto/response/mypage/StudentProfileResponse.java
backend/src/main/java/com/WEB4_5_GPT_BE/unihub/global/security/SecurityConfig.java
backend/src/main/resources/application-stg.yml
backend/src/test/java/com/WEB4_5_GPT_BE/unihub/domain/enrollment/controller/EnrollmentEventControllerTest.java

develop -> main

---

backend/src/main/java/com/WEB4_5_GPT_BE/unihub/domain/admin/controller/AdminController.java
backend/src/main/java/com/WEB4_5_GPT_BE/unihub/domain/enrollment/controller/EnrollmentEventController.java
backend/src/main/java/com/WEB4_5_GPT_BE/unihub/domain/member/dto/response/AdminLoginResponse.java
backend/src/main/java/com/WEB4_5_GPT_BE/unihub/domain/member/dto/response/MemberLoginResponse.java
backend/src/main/java/com/WEB4_5_GPT_BE/unihub/domain/member/dto/response/mypage/ProfessorProfileResponse.java
backend/src/main/java/com/WEB4_5_GPT_BE/unihub/domain/member/dto/response/mypage/StudentProfileResponse.java
backend/src/main/java/com/WEB4_5_GPT_BE/unihub/domain/member/service/AuthServiceImpl.java
backend/src/main/java/com/WEB4_5_GPT_BE/unihub/global/security/SecurityConfig.java
backend/src/main/resources/application-stg.yml
backend/src/test/java/com/WEB4_5_GPT_BE/unihub/domain/enrollment/controller/EnrollmentEventControllerTest.java
backend/src/test/java/com/WEB4_5_GPT_BE/unihub/domain/member/controller/MemberControllerTest.java
backend/src/test/java/com/WEB4_5_GPT_BE/unihub/domain/member/service/AuthServiceImplTest.java

develop -> main으로 배포

---

backend/src/main/java/com/WEB4_5_GPT_BE/unihub/domain/course/controller/CourseController.java
backend/src/main/java/com/WEB4_5_GPT_BE/unihub/domain/course/repository/CourseRepository.java
backend/src/main/java/com/WEB4_5_GPT_BE/unihub/domain/course/service/CourseService.java
backend/src/test/java/com/WEB4_5_GPT_BE/unihub/domain/course/controller/CourseControllerTest.java
backend/src/test/java/com/WEB4_5_GPT_BE/unihub/domain/course/service/CourseServiceTest.java

서준식/feat 106 학년,학기,전공에 대한 필터링 추가

---

backend/src/main/java/com/WEB4_5_GPT_BE/unihub/domain/admin/controller/AdminController.java
backend/src/main/java/com/WEB4_5_GPT_BE/unihub/domain/course/controller/CourseController.java
backend/src/main/java/com/WEB4_5_GPT_BE/unihub/domain/course/repository/CourseRepository.java
backend/src/main/java/com/WEB4_5_GPT_BE/unihub/domain/course/service/CourseService.java
backend/src/main/java/com/WEB4_5_GPT_BE/unihub/domain/enrollment/controller/EnrollmentEventController.java
backend/src/main/java/com/WEB4_5_GPT_BE/unihub/domain/member/dto/response/AdminLoginResponse.java
backend/src/main/java/com/WEB4_5_GPT_BE/unihub/domain/member/dto/response/MemberLoginResponse.java
backend/src/main/java/com/WEB4_5_GPT_BE/unihub/domain/member/dto/response/mypage/ProfessorProfileResponse.java
backend/src/main/java/com/WEB4_5_GPT_BE/unihub/domain/member/dto/response/mypage/StudentProfileResponse.java
backend/src/main/java/com/WEB4_5_GPT_BE/unihub/domain/member/service/AuthServiceImpl.java
backend/src/main/java/com/WEB4_5_GPT_BE/unihub/global/security/SecurityConfig.java
backend/src/main/resources/application-stg.yml
backend/src/test/java/com/WEB4_5_GPT_BE/unihub/domain/course/controller/CourseControllerTest.java
backend/src/test/java/com/WEB4_5_GPT_BE/unihub/domain/course/service/CourseServiceTest.java
backend/src/test/java/com/WEB4_5_GPT_BE/unihub/domain/enrollment/controller/EnrollmentEventControllerTest.java
backend/src/test/java/com/WEB4_5_GPT_BE/unihub/domain/member/controller/MemberControllerTest.java
backend/src/test/java/com/WEB4_5_GPT_BE/unihub/domain/member/service/AuthServiceImplTest.java

develop -> main ( 전공,학기,학년 필터링 추가 버전)

---

backend/src/main/java/com/WEB4_5_GPT_BE/unihub/domain/course/controller/CourseController.java

 swagger 문서 최신화( 필터링 파라미터 swagger에 추가)

---

backend/src/main/java/com/WEB4_5_GPT_BE/unihub/domain/member/service/EmailService.java
backend/src/test/java/com/WEB4_5_GPT_BE/unihub/domain/member/service/EmailServiceTest.java

이메일 로직 변경( 인증만료)

---

backend/src/main/java/com/WEB4_5_GPT_BE/unihub/domain/enrollment/controller/EnrollmentController.java
backend/src/main/java/com/WEB4_5_GPT_BE/unihub/global/Rq.java

- Member 도메인이 통합되면서 기존 rq.getActor 메서드를 통해 member의 id만을 가진 객체를 반환할 이유가 사라짐
- 수강신청 관련 메서드에서만 사용중이었기 때문에 getActor, getRealActor 제거
- 인증 방식을 AuthenticationPrincipal 파라메터를 통해 인증하도록 수정

옥정현/refactor : 수강신청 리펙토링

---

backend/src/main/java/com/WEB4_5_GPT_BE/unihub/domain/notice/controller/NoticeController.java
backend/src/main/java/com/WEB4_5_GPT_BE/unihub/domain/notice/dto/request/NoticeCreateRequest.java
backend/src/main/java/com/WEB4_5_GPT_BE/unihub/domain/notice/dto/request/NoticeUpdateRequest.java
backend/src/main/java/com/WEB4_5_GPT_BE/unihub/domain/notice/dto/response/NoticeCreateResponse.java
backend/src/main/java/com/WEB4_5_GPT_BE/unihub/domain/notice/dto/response/NoticeDeleteResponse.java
backend/src/main/java/com/WEB4_5_GPT_BE/unihub/domain/notice/dto/response/NoticeDetailResponse.java
backend/src/main/java/com/WEB4_5_GPT_BE/unihub/domain/notice/dto/response/NoticeListResponse.java
backend/src/main/java/com/WEB4_5_GPT_BE/unihub/domain/notice/dto/response/NoticeUpdateResponse.java
backend/src/main/java/com/WEB4_5_GPT_BE/unihub/domain/notice/entity/Notice.java
backend/src/main/java/com/WEB4_5_GPT_BE/unihub/domain/notice/repository/NoticeRepository.java
backend/src/main/java/com/WEB4_5_GPT_BE/unihub/domain/notice/service/NoticeService.java
backend/src/main/java/com/WEB4_5_GPT_BE/unihub/global/init/InitDataHelper.java
backend/src/main/java/com/WEB4_5_GPT_BE/unihub/global/init/InitTestData.java
backend/src/test/java/com/WEB4_5_GPT_BE/unihub/domain/notice/controller/NoticeControllerTest.java
backend/src/test/java/com/WEB4_5_GPT_BE/unihub/domain/notice/service/NoticeServiceTest.java

공지사항 작성
공지사항 목록 조회
공지사항 단건 조회
공지사항 수정
공지사항 삭제
관리자만 작성, 수정, 삭제 가능
학생 ,교직원은 조회만 가능

서준식/feat 119 공지사항

---

backend/src/main/java/com/WEB4_5_GPT_BE/unihub/domain/member/controller/MemberController.java
backend/src/main/java/com/WEB4_5_GPT_BE/unihub/domain/member/dto/response/mypage/MyPageAdminResponse.java
backend/src/main/java/com/WEB4_5_GPT_BE/unihub/domain/member/service/MemberService.java
backend/src/main/java/com/WEB4_5_GPT_BE/unihub/domain/member/service/MemberServiceImpl.java
backend/src/test/java/com/WEB4_5_GPT_BE/unihub/domain/member/controller/MemberControllerTest.java
backend/src/test/java/com/WEB4_5_GPT_BE/unihub/domain/member/service/MemberServiceImplTest.java

관리자 내 정보조회 - api 추가
비밀번호, 이메일 변경, 회원탈퇴는 기존의 기능 유지

서준식/feat 130 관리자 마이페이지

---

backend/src/main/java/com/WEB4_5_GPT_BE/unihub/domain/common/enums/CourseListReturnMode.java
backend/src/main/java/com/WEB4_5_GPT_BE/unihub/domain/course/controller/CourseController.java
backend/src/main/java/com/WEB4_5_GPT_BE/unihub/domain/course/dto/MyEnrollmentListForTimetableResponse.java
backend/src/main/java/com/WEB4_5_GPT_BE/unihub/domain/course/dto/TimetableCourseResponse.java
backend/src/main/java/com/WEB4_5_GPT_BE/unihub/domain/course/service/CourseService.java
backend/src/main/java/com/WEB4_5_GPT_BE/unihub/domain/enrollment/controller/EnrollmentController.java
backend/src/main/java/com/WEB4_5_GPT_BE/unihub/domain/enrollment/exception/RequiredParameterMissingException.java
backend/src/main/java/com/WEB4_5_GPT_BE/unihub/domain/enrollment/service/EnrollmentService.java

/api/courses 에서 timetable mode 추가
/api/enrollments/timetables/me 추가

강을찬/feat 126 강의에서 추가된 시간표 api 반영

---

backend/build.gradle
backend/src/main/java/com/WEB4_5_GPT_BE/unihub/domain/common/enums/Visibility.java
backend/src/main/java/com/WEB4_5_GPT_BE/unihub/domain/timetable/controller/TimetableController.java
backend/src/main/java/com/WEB4_5_GPT_BE/unihub/domain/timetable/dto/request/TimetableCreateRequest.java
backend/src/main/java/com/WEB4_5_GPT_BE/unihub/domain/timetable/dto/request/item/TimetableCourseAddRequest.java
backend/src/main/java/com/WEB4_5_GPT_BE/unihub/domain/timetable/dto/request/item/TimetableItemNormalCreateRequest.java
backend/src/main/java/com/WEB4_5_GPT_BE/unihub/domain/timetable/dto/request/share/TimetableShareLinkRequest.java
backend/src/main/java/com/WEB4_5_GPT_BE/unihub/domain/timetable/dto/response/TimetableDetailResponse.java
backend/src/main/java/com/WEB4_5_GPT_BE/unihub/domain/timetable/dto/response/TimetableItemScheduleResponse.java
backend/src/main/java/com/WEB4_5_GPT_BE/unihub/domain/timetable/dto/response/TimetableSemesterResponse.java
backend/src/main/java/com/WEB4_5_GPT_BE/unihub/domain/timetable/dto/response/item/TimetableItemDetailResponse.java
backend/src/main/java/com/WEB4_5_GPT_BE/unihub/domain/timetable/dto/response/item/TimetableItemResponse.java
backend/src/main/java/com/WEB4_5_GPT_BE/unihub/domain/timetable/dto/response/item/TimetableItemUpdateRequest.java
backend/src/main/java/com/WEB4_5_GPT_BE/unihub/domain/timetable/dto/response/share/TimetableShareLinkResponse.java
backend/src/main/java/com/WEB4_5_GPT_BE/unihub/domain/timetable/dto/response/share/TimetableSharedViewResponse.java
backend/src/main/java/com/WEB4_5_GPT_BE/unihub/domain/timetable/entity/Timetable.java
backend/src/main/java/com/WEB4_5_GPT_BE/unihub/domain/timetable/entity/TimetableItem.java
backend/src/main/java/com/WEB4_5_GPT_BE/unihub/domain/timetable/entity/TimetableItemSchedule.java
backend/src/main/java/com/WEB4_5_GPT_BE/unihub/domain/timetable/exception/TimetableException.java
backend/src/main/java/com/WEB4_5_GPT_BE/unihub/domain/timetable/exception/timetable/TimetableAlreadyExistsException.java
backend/src/main/java/com/WEB4_5_GPT_BE/unihub/domain/timetable/repository/TimetableRepository.java
backend/src/main/java/com/WEB4_5_GPT_BE/unihub/domain/timetable/service/TimetableItemService.java
backend/src/main/java/com/WEB4_5_GPT_BE/unihub/domain/timetable/service/TimetableItemServiceImpl.java
backend/src/main/java/com/WEB4_5_GPT_BE/unihub/domain/timetable/service/TimetableService.java
backend/src/main/java/com/WEB4_5_GPT_BE/unihub/domain/timetable/service/TimetableServiceImpl.java
backend/src/main/java/com/WEB4_5_GPT_BE/unihub/global/Rq.java
backend/src/test/java/com/WEB4_5_GPT_BE/unihub/domain/timetable/service/TimetableServiceImplTest.java

시간표 기능 도메인 (entity, dto)추가, Service, Controller 템플릿 추가

시간표 기능 도메인 (entity, dto)추가, Service, Controller 템플릿 추가

---

backend/src/test/java/com/WEB4_5_GPT_BE/unihub/domain/admin/service/AdminServiceTest.java

관리자 초대 테스트코드 수정

---

backend/src/main/java/com/WEB4_5_GPT_BE/unihub/domain/member/dto/response/mypage/CourseScheduleResponse.java
backend/src/main/java/com/WEB4_5_GPT_BE/unihub/domain/notice/entity/Notice.java
backend/src/main/java/com/WEB4_5_GPT_BE/unihub/domain/notice/repository/NoticeRepository.java
backend/src/main/java/com/WEB4_5_GPT_BE/unihub/domain/notice/scheduler/NoticePurgeScheduler.java

엔티티에 인덱스 추가( 현재 공지사항 삭제가 소프트 삭제로 구현되어있음) 
-> 조회 시 is_deleted=false 인 것만 조회가 되도록 인덱스를 구성
스케줄러를 도입해서 삭제된지 30일이 지난것을 영구 삭제하도록 설정

서준식/refactor 147 공지사항 리팩토링

---

backend/src/main/java/com/WEB4_5_GPT_BE/unihub/domain/admin/controller/AdminController.java
backend/src/main/java/com/WEB4_5_GPT_BE/unihub/domain/admin/service/AdminService.java
backend/src/main/java/com/WEB4_5_GPT_BE/unihub/domain/course/repository/EnrollmentPeriodRepository.java

lazy initialize 에러 문제 해결
query string 누락 시 400 에러와 메시지

강을찬/bug 152 admin 수강 신청 기간 조회 에러

---

backend/src/main/java/com/WEB4_5_GPT_BE/unihub/global/alert/AlertNotifier.java
backend/src/main/java/com/WEB4_5_GPT_BE/unihub/global/exception/GlobalExceptionHandler.java

 hotfix 성철님 코드 반영 안되거 적용

---

backend/src/main/java/com/WEB4_5_GPT_BE/unihub/domain/enrollment/controller/EnrollmentController.java
backend/src/main/java/com/WEB4_5_GPT_BE/unihub/domain/enrollment/exception/NoSessionException.java
backend/src/main/java/com/WEB4_5_GPT_BE/unihub/domain/enrollment/service/EnrollmentQueueService.java
backend/src/main/java/com/WEB4_5_GPT_BE/unihub/global/exception/GlobalExceptionHandler.java
backend/src/test/java/com/WEB4_5_GPT_BE/unihub/domain/enrollment/service/EnrollmentQueueServiceTest.java

수강신청 (enrollment controller) 관련 api 요청 시 대기열 뚫고 session 획득 여부 확인
session 이 없을 경우 403-1 return

강을찬/feat 160 수강신청 (enrollment controller) 관련 api 요청 시 대기열 뚫고 session 획득 여부 확인

---

backend/src/test/java/com/WEB4_5_GPT_BE/unihub/domain/admin/controller/AdminControllerTest.java

[test] admin controller test code 작성

---

backend/src/main/java/com/WEB4_5_GPT_BE/unihub/domain/enrollment/service/EnrollmentQueueService.java
backend/src/test/java/com/WEB4_5_GPT_BE/unihub/domain/enrollment/service/EnrollmentQueueServiceTest.java

[fix] 대기열 인원 수 확인 로직 변경 테스트 반영

---

backend/src/main/java/com/WEB4_5_GPT_BE/unihub/domain/enrollment/controller/EnrollmentEventController.java
backend/src/main/java/com/WEB4_5_GPT_BE/unihub/domain/enrollment/service/EnrollmentQueueService.java
backend/src/test/java/com/WEB4_5_GPT_BE/unihub/domain/enrollment/controller/EnrollmentEventControllerTest.java
backend/src/test/java/com/WEB4_5_GPT_BE/unihub/domain/enrollment/service/EnrollmentQueueServiceTest.java

강을찬/bug 182 수강신청 종료 후 세션 해지 시 버그 해결
